version: "3"
services:
  frontend:
    image: node:16.17-alpine3.16
    container_name: front_end
    command: sh -c "yarn > install.log && yarn start > dev-server.log"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./ui:/app
    depends_on:
      - backend

  backend:
    image: node:16.17-alpine3.16
    container_name: back_end
    command: sh -c "yarn > install.log && yarn start > server.log"
    restart: on-failure
    ports:
      - "5001:5001"
    working_dir: /app
    volumes:
      - ./nodejs:/app
